/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorCursos;
import javax.swing.JOptionPane;

/**
 *
 * @author MANBIR
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createCourse = new javax.swing.JButton();
        removeCourse = new javax.swing.JButton();
        openCourse = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCourse = new javax.swing.JList<>();
        labelCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Courses");

        createCourse.setText("Create Course");
        createCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCourseActionPerformed(evt);
            }
        });

        removeCourse.setText("Remove Course");
        removeCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCourseActionPerformed(evt);
            }
        });

        openCourse.setText("Open Course");
        openCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCourseActionPerformed(evt);
            }
        });

        listCourse.setModel(ControladorCursos.updateFolder());
        jScrollPane2.setViewportView(listCourse);

        labelCount.setText("Numbers of course: " + ControladorCursos.countCourse());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(openCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(createCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createCourse)
                .addGap(18, 18, 18)
                .addComponent(removeCourse)
                .addGap(18, 18, 18)
                .addComponent(openCourse)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update() {
        listCourse.setModel(ControladorCursos.updateFolder());
        labelCount.setText("Numbers of course: " + ControladorCursos.countCourse());
    }

    private void openCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCourseActionPerformed
        // TODO add your handling code here:
        String courseName = listCourse.getSelectedValue();
        
        if (courseName != null) {
            java.awt.EventQueue.invokeLater(() -> {
                new VentanaCurso(courseName).setVisible(true);
            });
            dispose();
        }
    }//GEN-LAST:event_openCourseActionPerformed

    private void removeCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCourseActionPerformed
        // TODO add your handling code here:
        String courseName = listCourse.getSelectedValue();
        if (courseName != null) {
            ControladorCursos.removeCourse(courseName);
            update();
        }
    }//GEN-LAST:event_removeCourseActionPerformed

    private void createCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCourseActionPerformed
        // TODO add your handling code here:
        String courseName = JOptionPane.showInputDialog("Please, enter the course:");
        if (courseName != null) {
            ControladorCursos.createCourse(courseName); 
            update();
        }
    }//GEN-LAST:event_createCourseActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createCourse;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCount;
    private javax.swing.JList<String> listCourse;
    private javax.swing.JButton openCourse;
    private javax.swing.JButton removeCourse;
    // End of variables declaration//GEN-END:variables
}
